name: Test Runner
on:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Make runner executable
        run: chmod +x ./src/test/java/com/spartawebtest/runner/Runner.java
      - name: Run tests
        run: ./src/test/java/com/spartawebtest/runner/Runner.java
